matrix:
  include:
# first the python tests
    - language: python
      python: 2.7
      install:
        - pip install -r tests/requirements.txt
      before_script:
        - cd tests
      script:
        - pytest
    - language: python
      python: 3.6
      install:
        - pip install -r tests/requirements.txt
      before_script:
        - cd tests
      script:
        - pytest
# next the python formatting
    - language: python
      python: 2.7
      install:
        - pip install yapf==0.25.0
      script:
        - yapf --diff --exclude venv/ --exclude .git/ -r .
# next the C++ tests
    - language: cpp
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      before_script:
        - cd redeem/path_planner
        - mkdir GCC
        - cd GCC
      script:
        - CC=gcc-7 CXX=g++-7 cmake ..
        - make -j
        - tests/PathPlannerTests
# and finally the C++ formatting
    - language: cpp
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - clang-format-6.0
      script:
        - .travis/format-cpp.sh
