#!/bin/sh

# Set perms on files that need to change from install.
chmod 755 /etc/initramfs-tools/hooks/dtbo
chmod 755 /lib/systemd/system/redeem.service

# Enable redeem.service
systemctl enable redeem.service

#Dowload and place replicpe dtb in right folder.
#todo!

# Change the dtb to that of replicape. Not tested!
#echo "dtb=am335x-boneblack-replicape.dtb" >> /boot/uEnv.txt

